### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by i3p9** [i3p9/LyriCatch#1]
- [x] Detect currently playing song from spotify without using API (macOS)
- [x] Detect currently playing song from spotify without using API (Windows)
- [ ] Make alternative parser for 100% coverage of lyrics
- [ ] Have currently playing song's album art shown (maybe via Spotify URL?)
- [ ] Crawler for azlyrics and musixmatch
- [x] Preferences panel for genius api
